export const TODO_LIST_LOADED = 'TODO_LIST_LOADED';
export const NEW_TODO_ADDED = 'NEW_TODO_ADDED';
export const FILTER_CHANGED = 'FILTER_CHANGED';
export const MARK_ALL_AS_COMPLETED = 'MARK_ALL_AS_COMPLETED';
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';
export const REMOVE_COMPLETED = 'REMOVE_COMPLETED';